/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.praktikum_9;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class LihatDataPanel extends javax.swing.JPanel {
    private MainJFrame mainFrame;

    /**
     * Creates new form LihatDataPanel
     */
    public LihatDataPanel(MainJFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        loadData ();
    }
    
    private void loadData() {
        String[] coloumn = {"Nama", "NIM", "Prodi", "Jenis Kelamin", "Status"};
        DefaultTableModel table = new DefaultTableModel(null, coloumn);
        
        for (Mahasiswa mhs: Mahasiswa.mahasiswas) {
            table.addRow(new String[] {
                mhs.getNama(),
                mhs.getNim(),
                mhs.getProdi(),
                mhs.getJenisKelamin(),
                mhs.isActive() ? "Aktif" : "Tidak aktif"
            });
        }
        
        
        
       LihatDataTable.setModel(table); 
       LihatDataTable.getTableHeader().setReorderingAllowed(false);
       
        LihatDataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = LihatDataTable.getSelectedRow();
                if (row != -1) {
                    Object[] options = {"Update", "Delete", "Close"};
                    
                    int pilihan = JOptionPane.showOptionDialog(
                            null, "Pilihan anda", "Update/Delete", JOptionPane.YES_NO_CANCEL_OPTION, 
                            JOptionPane.PLAIN_MESSAGE,
                            null, options, options[0]);
                    
                    if (pilihan == 0) {
                        mainFrame.changeMainPanel(new TambahDataPanel(Mahasiswa.mahasiswas.get(row)));
                    } else if (pilihan == 1) {
                        int konfirmasi = JOptionPane.showConfirmDialog(null,
                                "Yakin ingin menghapus data ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                        if (konfirmasi == JOptionPane.YES_OPTION) {
                            Mahasiswa.mahasiswas.remove(row);
                            table.removeRow(row);
                            JOptionPane.showMessageDialog(null, "Data telah dihapus!");
                        }
                    } else {
                        return;
                    }
                }
            }
        });
        
        
   
        
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LihatDataTable = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Lihat Data Mahasiswa");

        LihatDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(LihatDataTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable LihatDataTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
