/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.praktikum_9;

import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class TambahDataPanel extends javax.swing.JPanel {
    private boolean isUpdateMode = false;
    private Mahasiswa mahasiswaUpdate = null;
 
    public TambahDataPanel() {
        initComponents();
    }
    
     public TambahDataPanel(Mahasiswa mahasiswa) {
        initComponents();
        this.isUpdateMode = true;
        this.mahasiswaUpdate = mahasiswa;
        
        NamaTextField.setText(mahasiswa.getNama());
        NimTextField.setText(mahasiswa.getNim());
        ProdiComboBox.setSelectedItem(mahasiswa.getProdi());
        if (mahasiswa.getJenisKelamin().equalsIgnoreCase("Laki-laki")) {
            JenisKelaminLakiLakiRadioButton.setSelected(true);
        } else {
            JenisKelaminPerempuanRadioButton.setSelected(true);
        }
        aktifCheckBox.setSelected(mahasiswa.isActive());
        
        kirimButton.setText("Update");
        TambahDataMahasiswaLabel.setText("Update Data Mahasiswa");
    }
     
     

    private void clearForm (){
        NamaTextField.setText ("");
        NimTextField.setText ("");
        jenisKelaminButtonGroup.clearSelection();
        aktifCheckBox.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisKelaminButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        TambahDataMahasiswaLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JenisKelaminjLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NamaTextField = new javax.swing.JTextField();
        NimTextField = new javax.swing.JTextField();
        ProdiComboBox = new javax.swing.JComboBox<>();
        JenisKelaminLakiLakiRadioButton = new javax.swing.JRadioButton();
        JenisKelaminPerempuanRadioButton = new javax.swing.JRadioButton();
        aktifCheckBox = new javax.swing.JCheckBox();
        kirimButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(530, 400));
        setLayout(new java.awt.CardLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(530, 400));

        TambahDataMahasiswaLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TambahDataMahasiswaLabel.setText("Tambah Data Mahasiswa");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nim");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Prodi");

        JenisKelaminjLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JenisKelaminjLabel.setText("Jenis Kelamin");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Status");

        NamaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaTextFieldActionPerformed(evt);
            }
        });

        NimTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NimTextFieldActionPerformed(evt);
            }
        });

        ProdiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teknik Informatika", "Teknik Elektro", "Teknik Sipil", "Teknik Kimia" }));
        ProdiComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdiComboBoxActionPerformed(evt);
            }
        });

        jenisKelaminButtonGroup.add(JenisKelaminLakiLakiRadioButton);
        JenisKelaminLakiLakiRadioButton.setText("Laki Laki");

        jenisKelaminButtonGroup.add(JenisKelaminPerempuanRadioButton);
        JenisKelaminPerempuanRadioButton.setText("Perempuan");
        JenisKelaminPerempuanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JenisKelaminPerempuanRadioButtonActionPerformed(evt);
            }
        });

        aktifCheckBox.setText("Aktif");

        kirimButton.setBackground(new java.awt.Color(0, 153, 255));
        kirimButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kirimButton.setText("Kirim");
        kirimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirimButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TambahDataMahasiswaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(67, 67, 67))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(76, 76, 76)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(JenisKelaminjLabel)
                                    .addComponent(jLabel6))
                                .addGap(23, 23, 23)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aktifCheckBox)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JenisKelaminLakiLakiRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JenisKelaminPerempuanRadioButton))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(NimTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addComponent(NamaTextField)
                                .addComponent(ProdiComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(kirimButton))))
                .addGap(102, 102, 102))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(TambahDataMahasiswaLabel)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NamaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ProdiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JenisKelaminjLabel)
                    .addComponent(JenisKelaminLakiLakiRadioButton)
                    .addComponent(JenisKelaminPerempuanRadioButton))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(aktifCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(kirimButton)
                .addGap(33, 33, 33))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void NimTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NimTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NimTextFieldActionPerformed

    private void NamaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaTextFieldActionPerformed

    private void ProdiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdiComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdiComboBoxActionPerformed

    private void JenisKelaminPerempuanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JenisKelaminPerempuanRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JenisKelaminPerempuanRadioButtonActionPerformed

    private void kirimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kirimButtonActionPerformed
        // TODO add your handling code here:
      String nama = NamaTextField.getText ();
      String nim = NimTextField.getText();
      String prodi = (String) ProdiComboBox.getSelectedItem ();
      String jenisKelamin = JenisKelaminLakiLakiRadioButton.isSelected ()? "Laki-Laki" : "Perempuan";
      boolean isActive = aktifCheckBox.isSelected();
    
    if(nama.isEmpty() || nim.isEmpty() || !(JenisKelaminLakiLakiRadioButton.isSelected() 
            || JenisKelaminPerempuanRadioButton.isSelected())){
            JOptionPane.showMessageDialog(this, "Gagal menambahkan data\n"
                    + "Mohon melengkapi data terlebih dahulu!");
            return;
        }
        try{
            long nimLong = Long.parseLong(nim);
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Gagal menambahkan data\n"
                    + "NIM harus berupa angka!");
            return;
        }
        
        
        if(isUpdateMode && mahasiswaUpdate != null){
            mahasiswaUpdate.setNama(nama);
            mahasiswaUpdate.setNim(nim);
            mahasiswaUpdate.setProdi(prodi);
            mahasiswaUpdate.setJenisKelamin(jenisKelamin);
            mahasiswaUpdate.setActive(isActive);
            
            for(Mahasiswa m : Mahasiswa.mahasiswas){
                if(!m.equals(mahasiswaUpdate) && m.getNim().equals(nim)){
                    JOptionPane.showMessageDialog(this, "Gagal menambahkan data\n"
                            + "Data mahasiswa dengan NIM " + 
                            nim + " sudah ada", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            
            JOptionPane.showMessageDialog(this, "Data mahasiswa berhasil diperbarui", "Success", 
                    JOptionPane.PLAIN_MESSAGE);
            clearForm();
            
        }    else {
            for(Mahasiswa m : Mahasiswa.mahasiswas){
                if(m.getNim().equals(nim)){
                    JOptionPane.showMessageDialog(this, "Gagal menambahkan data\nData mahasiswa dengan NIM " + nim + " sudah ada", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        
      Mahasiswa mahasiswa = new Mahasiswa (nama, nim, prodi, jenisKelamin, isActive);
      Mahasiswa.mahasiswas.add(mahasiswa);
      
      JOptionPane.showMessageDialog (this, " Sukses menambahkan data mahasiswa " + nama);
      clearForm ();
        }
    }//GEN-LAST:event_kirimButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JenisKelaminLakiLakiRadioButton;
    private javax.swing.JRadioButton JenisKelaminPerempuanRadioButton;
    private javax.swing.JLabel JenisKelaminjLabel;
    private javax.swing.JTextField NamaTextField;
    private javax.swing.JTextField NimTextField;
    private javax.swing.JComboBox<String> ProdiComboBox;
    private javax.swing.JLabel TambahDataMahasiswaLabel;
    private javax.swing.JCheckBox aktifCheckBox;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup jenisKelaminButtonGroup;
    private javax.swing.JButton kirimButton;
    // End of variables declaration//GEN-END:variables
}
