/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.praktikum_9;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class lihatDataPanel extends javax.swing.JPanel {
    private MainJFrame mainFrame;
    /**
     * Creates new form lihatDataPanel
     */
    public lihatDataPanel(MainJFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        loadData();
    }

        private void loadData(){
            String [] coloumn = {"Nama", "Nim", "Prodi", "Jenis Kelamin", "Status"};
            DefaultTableModel table = new DefaultTableModel (null, coloumn);
                
        for (Mahasiswa mhs: Mahasiswa.mahasiswas) {
                    table.addRow(new String[] {
                        mhs.getNama(),
                        mhs.getNim(),
                        mhs.getProdi(),
                        mhs.getJenisKelamin(),
                        mhs.isActive() ? "Aktif" : "Tidak aktif"
                    });
                }
               lihatDataTable.setModel(table);
               
               lihatDataTable.addMouseListener(new java.awt.event.MouseAdapter() {
                    @Override
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        int row = lihatDataTable.getSelectedRow();
                        if (row != -1) {
                            Object[] options = {"Update", "Delete", "Close"};

                            int pilihan = JOptionPane.showOptionDialog(
                                    null, "Pilihan anda", "Update/Delete", 
                                    JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE,
                                    null, options, options[0]);

                            if (pilihan == 0) {
                                mainFrame.changeMainPanel(new TambahDataPanel(Mahasiswa.mahasiswas.get(row)));
                            } else if (pilihan == 1) {
                                int konfirmasi = JOptionPane.showConfirmDialog(null,
                                        "Yakin ingin menghapus data ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                                if (konfirmasi == JOptionPane.YES_OPTION) {
                                    Mahasiswa.mahasiswas.remove(row);
                                    table.removeRow(row);
                                    JOptionPane.showMessageDialog(null, "Data telah dihapus!");
                                }
                            } else {
                              return;
                            }
                        }
                    }
                });
        }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lihatDataTable = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(530, 400));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Lihat Data Mahasiswa");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 300));

        lihatDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(lihatDataTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lihatDataTable;
    // End of variables declaration//GEN-END:variables
}
