/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.praktikum_9;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class TambahDataPanel extends javax.swing.JPanel {
    private boolean isUpdateMode = false;
    private Mahasiswa mahasiswaUpdate = null;

    public TambahDataPanel() {
        initComponents();      
    }
    public TambahDataPanel(Mahasiswa mahasiswa) {
            initComponents();
            this.isUpdateMode = true;
            this.mahasiswaUpdate = mahasiswa;

            namaTextField.setText(mahasiswa.getNama());
            nimTextField.setText(mahasiswa.getNim());
            ProdiComboBox.setSelectedItem(mahasiswa.getProdi());
            if (mahasiswa.getJenisKelamin().equalsIgnoreCase("Laki-laki")) {
                lkRadioButton.setSelected(true);
            } else {
                prRadioButton.setSelected(true);
            }
            mhsAktifCheckBox.setSelected(mahasiswa.isActive());

            submitTambahData.setText("Update");
        }
    
    private void clearForm(){
        namaTextField.setText("");
        nimTextField.setText("");
        lkRadioButton.setSelected(false);
        prRadioButton.setSelected(false);
        mhsAktifCheckBox.setSelected(false);
    } 
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        nimLabel = new javax.swing.JLabel();
        prodiLabel = new javax.swing.JLabel();
        jenisKelaminLabel = new javax.swing.JLabel();
        mhsAktifLabel = new javax.swing.JLabel();
        namaTextField = new javax.swing.JTextField();
        nimTextField = new javax.swing.JTextField();
        ProdiComboBox = new javax.swing.JComboBox<>();
        lkRadioButton = new javax.swing.JRadioButton();
        prRadioButton = new javax.swing.JRadioButton();
        mhsAktifCheckBox = new javax.swing.JCheckBox();
        submitTambahData = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(229, 240, 252));
        jPanel1.setPreferredSize(new java.awt.Dimension(530, 400));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tambah Data Mahasiswa");

        namaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namaLabel.setText("Nama");

        nimLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nimLabel.setText("NIM");

        prodiLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        prodiLabel.setText("Prodi");

        jenisKelaminLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jenisKelaminLabel.setText("Jenis Kelamin");

        mhsAktifLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mhsAktifLabel.setText("Status");

        namaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextFieldActionPerformed(evt);
            }
        });

        nimTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimTextFieldActionPerformed(evt);
            }
        });

        ProdiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S1 Teknik Informatika", "S1 Teknik Elektro", "D3 Teknik Elektro" }));
        ProdiComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdiComboBoxActionPerformed(evt);
            }
        });

        buttonGroup1.add(lkRadioButton);
        lkRadioButton.setText("Laki-Laki");
        lkRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lkRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(prRadioButton);
        prRadioButton.setText("Perempuan");
        prRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prRadioButtonActionPerformed(evt);
            }
        });

        mhsAktifCheckBox.setText("Mahasiswa Aktif");
        mhsAktifCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mhsAktifCheckBoxActionPerformed(evt);
            }
        });

        submitTambahData.setBackground(new java.awt.Color(0, 51, 102));
        submitTambahData.setForeground(new java.awt.Color(255, 255, 255));
        submitTambahData.setText("Submit");
        submitTambahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitTambahDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(156, 156, 156))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitTambahData, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nimLabel)
                            .addComponent(prodiLabel)
                            .addComponent(mhsAktifLabel)
                            .addComponent(jenisKelaminLabel)
                            .addComponent(namaLabel))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProdiComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nimTextField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mhsAktifCheckBox)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lkRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(prRadioButton)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaLabel)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nimLabel)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodiLabel)
                    .addComponent(ProdiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisKelaminLabel)
                    .addComponent(lkRadioButton)
                    .addComponent(prRadioButton))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mhsAktifLabel)
                    .addComponent(mhsAktifCheckBox))
                .addGap(30, 30, 30)
                .addComponent(submitTambahData, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void nimTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimTextFieldActionPerformed

    private void prRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prRadioButtonActionPerformed

    private void lkRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lkRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lkRadioButtonActionPerformed

    private void mhsAktifCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mhsAktifCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mhsAktifCheckBoxActionPerformed

    private void ProdiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdiComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdiComboBoxActionPerformed

    private void namaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTextFieldActionPerformed

    private void submitTambahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitTambahDataActionPerformed
        // TODO add your handling code here:
        String nama = namaTextField.getText();
        String nim = nimTextField.getText();
        String prodi = (String)ProdiComboBox.getSelectedItem();
        String jenisKelamin = lkRadioButton.isSelected() ? "Laki-Laki" : "Perempuan";
        boolean isActive = mhsAktifCheckBox.isSelected();
        
        Mahasiswa mahasiswa = new Mahasiswa (nama, nim, prodi, jenisKelamin, isActive);
        Mahasiswa.mahasiswas.add(mahasiswa);
        
        if(nama.isEmpty() || nim.isEmpty() || !(lkRadioButton.isSelected() || prRadioButton.isSelected())){
            JOptionPane.showMessageDialog(this, "Gagal menambahkan data\nMohon melengkapi data terlebih dahulu!",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try{
            long nimLong = Long.parseLong(nim);
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Gagal menambahkan data\nNIM harus berupa angka!",  "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
            
        if(isUpdateMode && mahasiswaUpdate != null){
            mahasiswaUpdate.setNama(nama);
            mahasiswaUpdate.setNim(nim);
            mahasiswaUpdate.setProdi(prodi);
            mahasiswaUpdate.setJenisKelamin(jenisKelamin);
            mahasiswaUpdate.setActive(isActive);
            
            
            JOptionPane.showMessageDialog(this, "Data mahasiswa berhasil diperbarui", "Success", 
                    JOptionPane.PLAIN_MESSAGE);
            clearForm();
            for(Mahasiswa m : Mahasiswa.mahasiswas){
                if(!m.equals(mahasiswaUpdate) && m.getNim().equals(nim)){
                    JOptionPane.showMessageDialog(this, "Gagal menambahkan data\nData mahasiswa dengan NIM " + 
                            nim + " sudah ada", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            
            JOptionPane.showMessageDialog(this, "Data mahasiswa berhasil diperbarui", "Success", 
                    JOptionPane.PLAIN_MESSAGE);
            clearForm();
        } else {
            for(Mahasiswa m : Mahasiswa.mahasiswas){
                if(m.getNim().equals(nim)){
                    JOptionPane.showMessageDialog(this, "Gagal menambahkan data\nData mahasiswa dengan NIM "
                            + nim + " sudah ada", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            Mahasiswa mahasiswas = new  Mahasiswa(nama, nim, prodi, jenisKelamin, isActive);
            Mahasiswa.mahasiswas.add(mahasiswas);

            JOptionPane.showMessageDialog(this, "Sukses menambahkan data mahasiswa "
                    + nama, "Success", JOptionPane.INFORMATION_MESSAGE);
            clearForm();
        }
    }//GEN-LAST:event_submitTambahDataActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ProdiComboBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jenisKelaminLabel;
    private javax.swing.JRadioButton lkRadioButton;
    private javax.swing.JCheckBox mhsAktifCheckBox;
    private javax.swing.JLabel mhsAktifLabel;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JLabel nimLabel;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JRadioButton prRadioButton;
    private javax.swing.JLabel prodiLabel;
    private javax.swing.JButton submitTambahData;
    // End of variables declaration//GEN-END:variables
}
